M48
; DRILL file {KiCad (6.0.5)} date Sat Aug  3 11:58:09 2024
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-08-03T11:58:09+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.5)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.100
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C1.600
%
G90
G05
T1
X127.6Y-87.61
X127.6Y-93.39
T2
X152.6Y-102.0
T3
X152.6Y-81.0
T0
M30
